### ISSUE TITLE
Vehicle despawn/spawn if player freezed out

### ISSUE THREAD

**Issue by dorn3r** [Stuyk/altv-athena-issues#46]
### Description of the problem

My settings:
SPAWN_ALL_VEHICLES_ON_START: false,
SPAWN_VEHICLES_ON_JOIN: true,
DESPAWN_VEHICLES_ON_LOGOUT: true,

If player freezed out/crash, and come back then old vehicles stayed, but new too spawned

Error in console:

[21:26:26] DelMar_Mila has logged out.
TypeError: Cannot read properties of undefined (reading 'owner')
    at file:///C:/Users/Administrator/Desktop/hood-athena/resources/core/server/extensions/vehicleFuncs.js:477:57
    at Array.filter (<anonymous>)
    at Function.despawnAll (file:///C:/Users/Administrator/Desktop/hood-athena/resources/core/server/extensions/vehicleFuncs.js:477:11)
    at tryDisconnect (file:///C:/Users/Administrator/Desktop/hood-athena/resources/core/server/systems/login.js:121:26)

### Reproduction steps

Set this settings, and make a crash to player

### Expected behaviour

.

### Additional context

.

### Version

last master branch

**Comment by Stuyk** [comment]
There are two solutions we can go with:

1. SPAWN_VEHICLES_ON_JOIN
-> Make it so that all vehicles are compared against existing vehicles before spawning.
2. DESPAWN_VEHICLES_ON_LOGOUT
-> Make a tick that checks if the character is online for the owner of that vehicle. Also have to check if a vehicle is faction related so may need a flag for isFactionVehicle or something.

**Comment by Stuyk** [comment]
Tagged the wrong issue. Ignore the above commit.

**Comment by Stuyk** [comment]
@dorn3r Need confirmation on this fix.
